services:
  - type: web
    name: keiba-api
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: file:./prisma/dev.db
      - key: NODE_ENV
        value: production
